select * from [dbo].[customer_data];


--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) as revenue
from customer_data
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from customer_data
where discount_applied = 'Yes' and purchase_amount>= (select avg(purchase_amount) from customer_data);

--Q3. Which are the top 5 products with the highest average review rating?

select top 5 item_purchased,round(avg(review_rating),2) as Average_Review_Rating
from customer_data
group by item_purchased
order by avg(review_rating) desc


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,round(avg(purchase_amount),2)
from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
count(customer_id) as total_customers,
avg(purchase_amount) as average_spend,
sum(purchase_amount) as total_revenue
from customer_data
group by subscription_status
order by total_revenue,average_spend,total_customers desc

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
    item_purchased,
    ROUND(
        SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) * 100.0 / COUNT(*), 2
    ) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id,previous_purchases,
case
    when previous_purchases=1 then 'New'
    when previous_purchases between 2 AND 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer_data)
select customer_segment,count(*) as "Number of customers"
from customer_type
group by customer_segment;


--Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS(
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER
        (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeated_Buyers
from customer_data
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue  desc